return require('./wrapper.lua')(function (...)
  local LunaStream = require("./src")()
  LunaStream:setupAddon()
  LunaStream:setupRoutes()
  LunaStream:setupWebsocket()
  LunaStream:start()
end, ...)